"""
Fix service — creates a GitHub branch with AI-suggested patches.
"""
import os
import logging
from typing import Optional

logger = logging.getLogger(__name__)


class FixService:
    """Apply AI-generated fixes by creating a new branch via GitHub API."""

    @staticmethod
    async def apply_fixes(
        repo_url: str,
        vulnerabilities: list,
        github_token: str,
    ) -> dict:
        """
        Create a new branch with fix commits for the given vulnerabilities.
        Returns dict with branch name and PR URL.
        """
        try:
            from github import Github, GithubException
        except ImportError:
            raise RuntimeError("PyGitHub is required: pip install PyGithub")

        # Parse owner/repo from URL
        parts = repo_url.rstrip("/").split("/")
        owner, repo_name = parts[-2], parts[-1]

        g = Github(github_token)
        try:
            repo = g.get_repo(f"{owner}/{repo_name}")
        except GithubException as e:
            raise RuntimeError(f"Cannot access repository: {e}")

        # Get default branch
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        sha = ref.object.sha

        # Create fix branch
        branch_name = f"repoguard/security-fixes-{sha[:7]}"
        try:
            repo.create_git_ref(f"refs/heads/{branch_name}", sha)
        except GithubException:
            # Branch might already exist
            pass

        # Apply fixes that have file paths and suggestions
        fixes_applied = 0
        for vuln in vulnerabilities:
            if not vuln.fix_suggestion or not vuln.file_path:
                continue
            try:
                # Get current file content
                file_content = repo.get_contents(vuln.file_path, ref=branch_name)
                if isinstance(file_content, list):
                    continue  # Skip directories

                # Create commit message
                commit_msg = f"fix: {vuln.title}\n\nSeverity: {vuln.severity}\nTool: {vuln.tool}\n\nSuggested fix applied by RepoGuard AI"

                # Note: In a real implementation, we would parse the fix_suggestion
                # and apply it to the actual code. For now, we add a comment.
                current = file_content.decoded_content.decode("utf-8")
                if vuln.code_snippet and vuln.code_snippet in current:
                    # Add a TODO comment above the vulnerable code
                    patched = current.replace(
                        vuln.code_snippet,
                        f"# TODO [RepoGuard AI]: {vuln.fix_suggestion}\n{vuln.code_snippet}",
                    )
                    repo.update_file(
                        vuln.file_path,
                        commit_msg,
                        patched,
                        file_content.sha,
                        branch=branch_name,
                    )
                    fixes_applied += 1
            except Exception as e:
                logger.warning(f"Could not apply fix for {vuln.file_path}: {e}")

        # Create PR
        try:
            pr = repo.create_pull(
                title=f"🛡️ RepoGuard AI: {fixes_applied} Security Fixes",
                body=(
                    f"## RepoGuard AI Security Audit\n\n"
                    f"This PR addresses **{fixes_applied}** security findings identified during the automated scan.\n\n"
                    f"⚠️ **Review each change carefully before merging.**\n\n"
                    f"Generated by [RepoGuard AI](https://repoguard.ai)"
                ),
                head=branch_name,
                base=default_branch,
            )
            return {"branch": branch_name, "pr_url": pr.html_url}
        except GithubException as e:
            return {"branch": branch_name, "pr_url": f"https://github.com/{owner}/{repo_name}/compare/{branch_name}"}
